---
name: "Ansible Integration Test"
on:
  workflow_call:
    inputs:
      targets:
        required: true
        type: string
      ansible-core-versions:
        required: false
        default: '["stable-2.14"]'
        type: string
      target-python-versions:
        required: false
        default: '["default"]'
        type: string

jobs:
  ansible-test-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets: ${{ fromJson(inputs.targets) }}
        ansible-core-versions: ${{ fromJson(inputs.ansible-core-versions) }}
        target-python-versions: ${{ fromJson(inputs.target-python-versions) }}

    name: "${{ matrix.targets.name }}-${{ matrix.ansible-core-versions }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .tmp-collection

      - name: "Install ansible-test-molecule"
        uses: actions/download-artifact@v3
        with:
          name: ansible-test-molecule
          path: .tmp-collection/tests/integration/targets/${{ matrix.targets.test }}

      - name: "ansible-test-molecule permissions"
        run: |
          chmod +x .tmp-collection/tests/integration/targets/${{ matrix.targets.test }}/runme.sh

      - name: "Perform ${{ matrix.targets.test }} integration test with ansible-test"
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          collection-src-directory: .tmp-collection
          ansible-core-version: ${{ matrix.ansible-core-versions }}
          target-python-version: ${{ matrix.target-python-versions }}
          controller-python-version: auto
          docker-image: "--docker-privileged"  # Workaround because ansible-test action doesn't support setting privileged flag
          testing-type: integration
          target: ${{ matrix.targets.test }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
