---
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
permissions:
  pull-requests: write
name: "Auto label pull request"
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: "Confirm correct pull request title"
        uses: mmubeen/action-pr-title@master # until PR gets merged https://github.com/deepakputhraya/action-pr-title/pull/29
        with:
          allowed_prefixes: 'feat,feature,fix,major,breaking,minor,enhancement,deprecated,removed,security,bug,bugfix,docs,packaging,test,refactor,refactoring,skip-release,skip_changelog'

      - name: "Apply label"
        if: "github.event.pull_request.labels.length == 0"
        uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: |
              {
              "feature": "enhancement",
              "feat": "enhancement",
              "fix": "bugfix",
              "major": "major",
              "breaking": "breaking",
              "minor": "minor",
              "enhancement": "enhancement",
              "deprecated": "deprecated",
              "removed": "removed",
              "security": "security",
              "bug": "bug",
              "bugfix": "bugfix",
              "docs": "trivial",
              "packaging": "trivial",
              "test": "trivial",
              "refactor": "trivial",
              "refactoring": "trivial",
              "skip-release": "skip_changelog",
              "skip_changelog": "skip_changelog"
              }
