---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # it's necessary to fetch all tags

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $RELEASE_VERSION | cut -c 2-)

      - name: Update version in bash script
        run: |
          sed -i "s/^# Version:.*/# Version: ${VERSION}/" ansible-test-molecule.sh
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ansible-test-molecule.sh
          git commit -m "chore: bump version to ${VERSION}"
          git push
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
